from __future__ import annotations
import io, zipfile, html
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom import minidom
from .schema import Fixture, Channel

GDTF_ATTR_MAP = {
    "Pan": "Pan", "PanFine": "Pan", "Tilt": "Tilt", "TiltFine": "Tilt",
    "PanTiltSpeed": "PanTiltSpeed", "Dimmer": "Dimmer",
    "Shutter": "Shutter1", "Strobe": "Shutter1", "Red": "ColorAdd_R",
    "Green": "ColorAdd_G", "Blue": "ColorAdd_B", "White": "ColorAdd_W",
    "Amber": "ColorAdd_A", "UV": "ColorAdd_UV", "ColorMacro": "ColorMacro1",
    "Macro": "Macro1", "MacroSpeed": "Macro1Speed", "Reset": "Reset", "Control": "Control1",
    "Unknown": "Control1"
}

def _pretty_xml(elem: Element) -> bytes:
    rough = tostring(elem, encoding="utf-8")
    parsed = minidom.parseString(rough)
    return parsed.toprettyxml(indent="  ", encoding="utf-8")

def _attr(ch: Channel) -> str:
    return GDTF_ATTR_MAP.get(ch.attribute, GDTF_ATTR_MAP.get(ch.name, "Control1"))

def build_gdtf(fixture: Fixture, mode_name: str) -> bytes:
    mode = next(m for m in fixture.modes if m.name == mode_name)
    root = Element("GDTF", {"DataVersion":"1.1"})
    ft = SubElement(root, "FixtureType", {
        "Name": fixture.fixture_name,
        "ShortName": fixture.short_name or fixture.fixture_name[:12],
        "LongName": fixture.fixture_name,
        "Manufacturer": fixture.manufacturer,
        "Description": fixture.notes or "Generated by FixtureForge AI MVP",
        "FixtureTypeID": "00000000-0000-0000-0000-000000000001"
    })
    attr_defs = SubElement(ft, "AttributeDefinitions")
    attrs = SubElement(attr_defs, "Attributes")
    used = sorted(set(_attr(ch) for ch in mode.channels))
    for a in used:
        SubElement(attrs, "Attribute", {"Name": a, "Pretty": a, "ActivationGroup": "None", "Feature": "Control"})
    geos = SubElement(ft, "Geometries")
    base = SubElement(geos, "Geometry", {"Name":"Base", "Model":"BaseModel"})
    heads = sorted(set(ch.head for ch in mode.channels if ch.head)) or [1]
    for h in heads:
        SubElement(base, "Geometry", {"Name": f"Head_{h}", "Model":"HeadModel"})
    dmx_modes = SubElement(ft, "DMXModes")
    dm = SubElement(dmx_modes, "DMXMode", {"Name": mode.name, "Geometry":"Base"})
    dmx_channels = SubElement(dm, "DMXChannels")
    for ch in sorted(mode.channels, key=lambda c: c.channel):
        geometry = f"Head_{ch.head}" if ch.head else "Base"
        offset = str(ch.channel)
        if ch.resolution.lower() in ("16bit", "coarse"):
            fine = next((c for c in mode.channels if c.fine_of == ch.channel), None)
            if fine:
                offset = f"{ch.channel},{fine.channel}"
        if ch.resolution.lower() == "fine":
            continue
        dch = SubElement(dmx_channels, "DMXChannel", {
            "Geometry": geometry,
            "Offset": offset,
            "Default": str(ch.default),
            "Highlight": "255" if ch.attribute in ("Dimmer","Red","Green","Blue","White") else "0"
        })
        logical = SubElement(dch, "LogicalChannel", {"Attribute": _attr(ch)})
        func_attrs = {"Name": ch.name or _attr(ch), "Attribute": _attr(ch), "DMXFrom": "0/1", "Default": str(ch.default)}
        cf = SubElement(logical, "ChannelFunction", func_attrs)
        for i, vr in enumerate(ch.values):
            SubElement(cf, "ChannelSet", {"Name": vr.label, "DMXFrom": f"{vr.from_value}/1"})
    xml = _pretty_xml(root)
    thumb = b'<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128"><rect width="128" height="128" fill="#111"/><text x="64" y="70" fill="#fff" font-size="20" text-anchor="middle">GDTF</text></svg>'
    mem = io.BytesIO()
    with zipfile.ZipFile(mem, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("description.xml", xml)
        z.writestr("thumbnail.svg", thumb)
    return mem.getvalue()
