from __future__ import annotations

import io
import zipfile
import xml.etree.ElementTree as ET
from typing import Any, Dict


def build_basic_gdtf(fixture: Dict[str, Any]) -> bytes:
    manufacturer = fixture.get("manufacturer") or "Unknown"
    name = fixture.get("fixture_name") or "Unknown Fixture"

    root = ET.Element("GDTF", {"DataVersion": "1.1"})
    ft = ET.SubElement(root, "FixtureType", {
        "Name": name,
        "ShortName": name[:32],
        "LongName": f"{manufacturer} {name}",
        "Manufacturer": manufacturer,
        "Description": "Generated by FixtureForge AI v0.6",
    })

    ET.SubElement(ft, "AttributeDefinitions")
    geoms = ET.SubElement(ft, "Geometries")
    ET.SubElement(geoms, "Geometry", {"Name": "Base", "Model": ""})
    dmx_modes = ET.SubElement(ft, "DMXModes")

    for mode in fixture.get("modes", []):
        dmx_mode = ET.SubElement(dmx_modes, "DMXMode", {"Name": str(mode.get("name") or "Mode"), "Geometry": "Base"})
        dmx_channels = ET.SubElement(dmx_mode, "DMXChannels")
        for ch in mode.get("channels", []):
            channel_no = ch.get("channel")
            if not channel_no:
                continue
            attr = str(ch.get("attribute") or "NoFeature")
            dmx = ET.SubElement(dmx_channels, "DMXChannel", {
                "Geometry": "Base",
                "Offset": str(channel_no),
                "Default": str(ch.get("default_value") or 0),
                "Highlight": str(ch.get("highlight_value") or 0),
            })
            logical = ET.SubElement(dmx, "LogicalChannel", {"Attribute": attr, "Snap": "No", "Master": "None"})
            cf = ET.SubElement(logical, "ChannelFunction", {
                "Name": ch.get("raw_label") or attr,
                "Attribute": attr,
                "OriginalAttribute": attr,
                "DMXFrom": "0/1",
                "Default": str(ch.get("default_value") or 0),
            })
            for r in ch.get("ranges", []) or []:
                ET.SubElement(cf, "ChannelSet", {
                    "Name": r.get("name") or r.get("description") or "Range",
                    "DMXFrom": f"{int(r.get('from',0))}/1",
                    "PhysicalFrom": "0",
                    "PhysicalTo": "1",
                })

    xml_bytes = ET.tostring(root, encoding="utf-8", xml_declaration=True)
    mem = io.BytesIO()
    with zipfile.ZipFile(mem, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.writestr("description.xml", xml_bytes)
        z.writestr("thumbnail.svg", "<svg xmlns='http://www.w3.org/2000/svg' width='64' height='64'><rect width='64' height='64'/></svg>")
    return mem.getvalue()
