from __future__ import annotations

import io
import zipfile
import xml.etree.ElementTree as ET
from typing import Dict, Any
import pandas as pd


def mode_to_dataframe(mode: Dict[str, Any]) -> pd.DataFrame:
    rows = []
    for ch in mode.get("channels", []):
        ranges = ch.get("ranges") or []
        rows.append({
            "channel": ch.get("channel"),
            "fine_channel": ch.get("fine_channel"),
            "attribute": ch.get("attribute"),
            "raw_label": ch.get("raw_label"),
            "raw_description": ch.get("raw_description"),
            "geometry": ch.get("geometry"),
            "ranges": " | ".join([f"{r.get('from')}-{r.get('to')}: {r.get('name')}" for r in ranges])
        })
    return pd.DataFrame(rows)


def fixture_to_csv_bytes(fixture: Dict[str, Any]) -> bytes:
    out = io.StringIO()
    for mode in fixture.get("modes", []):
        out.write(f"# Mode: {mode.get('name')} ({mode.get('channel_count')}CH)\\n")
        out.write(mode_to_dataframe(mode).to_csv(index=False))
        out.write("\\n")
    return out.getvalue().encode("utf-8")


def build_simple_gdtf(fixture: Dict[str, Any]) -> bytes:
    # Basic GDTF-like ZIP for early testing. The channel map CSV/JSON is the reliable export in this build.
    manufacturer = fixture.get("manufacturer") or "Unknown"
    name = fixture.get("fixture_name") or "Unknown Fixture"

    root = ET.Element("GDTF", {"DataVersion": "1.2"})
    ft = ET.SubElement(root, "FixtureType", {
        "Name": name,
        "ShortName": name[:32],
        "LongName": f"{manufacturer} {name}",
        "Manufacturer": manufacturer,
        "Description": "Generated by FixtureForge AI v0.7"
    })
    ET.SubElement(ft, "AttributeDefinitions")
    geoms = ET.SubElement(ft, "Geometries")
    ET.SubElement(geoms, "Geometry", {"Name": "Base", "Model": ""})
    modes_el = ET.SubElement(ft, "DMXModes")

    for mode in fixture.get("modes", []):
        m = ET.SubElement(modes_el, "DMXMode", {"Name": str(mode.get("name")), "Geometry": "Base"})
        channels_el = ET.SubElement(m, "DMXChannels")
        for ch in mode.get("channels", []):
            offset = str(ch.get("channel"))
            attr = str(ch.get("attribute") or "NoFeature")
            dmx = ET.SubElement(channels_el, "DMXChannel", {"Geometry": "Base", "Offset": offset, "Default": "0", "Highlight": "0"})
            logical = ET.SubElement(dmx, "LogicalChannel", {"Attribute": attr, "Snap": "No", "Master": "None"})
            cf = ET.SubElement(logical, "ChannelFunction", {"Name": ch.get("raw_label") or attr, "Attribute": attr, "OriginalAttribute": attr, "DMXFrom": "0/1"})
            for r in ch.get("ranges", []) or []:
                ET.SubElement(cf, "ChannelSet", {"Name": r.get("name") or "Range", "DMXFrom": f"{int(r.get('from', 0))}/1"})

    xml = ET.tostring(root, encoding="utf-8", xml_declaration=True)
    mem = io.BytesIO()
    with zipfile.ZipFile(mem, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("description.xml", xml)
        z.writestr("thumbnail.svg", "<svg xmlns='http://www.w3.org/2000/svg' width='64' height='64'><rect width='64' height='64'/></svg>")
    return mem.getvalue()
