import csv
import io
import zipfile
import xml.etree.ElementTree as ET
from datetime import datetime
from typing import Dict, List


def _safe(s: str) -> str:
    return "".join(c if c.isalnum() or c in "._- " else "_" for c in str(s)).strip() or "fixture"


def _attr_to_gdtf(attribute: str) -> str:
    a = (attribute or "Unknown").lower().replace(" ", "")
    mapping = {
        "pan": "Pan", "panfine": "Pan", "tilt": "Tilt", "tiltfine": "Tilt",
        "dimmer": "Dimmer", "shutter": "Shutter1", "strobe": "Shutter1",
        "coloradd_r": "ColorAdd_R", "red": "ColorAdd_R",
        "coloradd_g": "ColorAdd_G", "green": "ColorAdd_G",
        "coloradd_b": "ColorAdd_B", "blue": "ColorAdd_B",
        "coloradd_w": "ColorAdd_W", "white": "ColorAdd_W",
        "colormacro": "ColorMacro1", "macro": "Macro1", "macrospeed": "Macro1Speed",
        "pantiltspeed": "PanTiltSpeed", "reset": "Control1", "unknown": "Control1",
    }
    return mapping.get(a, attribute.replace(" ", "") or "Control1")


def _fixture_channels(mode: Dict) -> List[Dict]:
    return sorted(mode.get("channels", []), key=lambda c: int(c.get("channel", 9999)))


def build_channel_csv(fixture: Dict) -> bytes:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["mode", "channel", "fixture_part", "raw_name", "attribute", "resolution", "fine_for_channel", "ranges"])
    for mode in fixture.get("modes", []):
        for ch in _fixture_channels(mode):
            ranges = "; ".join([f"{r.get('from')}-{r.get('to')}: {r.get('name')}" for r in ch.get("ranges", [])])
            writer.writerow([mode.get("mode_name"), ch.get("channel"), ch.get("fixture_part"), ch.get("raw_name"), ch.get("attribute"), ch.get("resolution"), ch.get("fine_for_channel"), ranges])
    return output.getvalue().encode("utf-8-sig")


def build_gdtf(fixture: Dict) -> bytes:
    # Minimal, best-effort GDTF package. It is intended as a generator baseline and should be validated in GDTF Builder / grandMA3.
    manufacturer = fixture.get("manufacturer") or "Unknown"
    name = fixture.get("fixture_name") or "Generated Fixture"

    root = ET.Element("GDTF", {"DataVersion": "1.2"})
    ft = ET.SubElement(root, "FixtureType", {
        "Name": name,
        "ShortName": name[:32],
        "LongName": f"{manufacturer} {name}",
        "Manufacturer": manufacturer,
        "FixtureTypeID": "00000000-0000-0000-0000-000000000001",
        "Thumbnail": "thumbnail",
    })
    ET.SubElement(ft, "Revision", {"Text": "Generated by Auto GDTF Builder MVP", "Date": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")})

    attr_defs = ET.SubElement(ft, "AttributeDefinitions")
    attrs = ET.SubElement(attr_defs, "Attributes")
    used_attrs = set()
    for mode in fixture.get("modes", []):
        for ch in _fixture_channels(mode):
            used_attrs.add(_attr_to_gdtf(ch.get("attribute")))
    for i, attr in enumerate(sorted(used_attrs)):
        ET.SubElement(attrs, "Attribute", {"Name": attr, "Pretty": attr, "ActivationGroup": "", "Feature": "Auto"})

    geoms = ET.SubElement(ft, "Geometries")
    ET.SubElement(geoms, "Geometry", {"Name": "Base", "Model": "Base"})
    heads = sorted({str(ch.get("fixture_part") or "Head") for mode in fixture.get("modes", []) for ch in _fixture_channels(mode)})
    for h in heads:
        if h.lower() not in ("", "base", "main", "fixture"):
            ET.SubElement(geoms, "Geometry", {"Name": _safe(h), "Model": "Head"})

    dmx_modes = ET.SubElement(ft, "DMXModes")
    for mode in fixture.get("modes", []):
        mode_el = ET.SubElement(dmx_modes, "DMXMode", {"Name": str(mode.get("mode_name") or f"{mode.get('channel_count','?')}CH"), "Geometry": "Base"})
        dmx_channels = ET.SubElement(mode_el, "DMXChannels")
        for ch in _fixture_channels(mode):
            attr = _attr_to_gdtf(ch.get("attribute"))
            offset = str(ch.get("channel"))
            if (ch.get("resolution") or "").lower() == "16bit_coarse":
                # find matching fine channel if present
                fine = next((x for x in _fixture_channels(mode) if x.get("fine_for_channel") == ch.get("channel")), None)
                if fine:
                    offset = f"{ch.get('channel')},{fine.get('channel')}"
            if (ch.get("resolution") or "").lower() == "16bit_fine":
                continue
            geom = _safe(ch.get("fixture_part") or "Base")
            dmx_ch = ET.SubElement(dmx_channels, "DMXChannel", {"Geometry": geom, "Offset": offset, "Highlight": str(ch.get("highlight_dmx") or 0), "Default": str(ch.get("default_dmx") or 0)})
            logical = ET.SubElement(dmx_ch, "LogicalChannel", {"Attribute": attr})
            ranges = ch.get("ranges") or [{"from": 0, "to": 255, "name": ch.get("raw_name") or attr}]
            for idx, r in enumerate(ranges):
                ET.SubElement(logical, "ChannelFunction", {
                    "Name": str(r.get("name") or attr),
                    "Attribute": attr,
                    "DMXFrom": str(r.get("from", 0)),
                    "DMXTo": str(r.get("to", 255)),
                    "OriginalAttribute": str(ch.get("attribute") or ""),
                })

    xml_bytes = ET.tostring(root, encoding="utf-8", xml_declaration=True)
    gdtf_buf = io.BytesIO()
    with zipfile.ZipFile(gdtf_buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("description.xml", xml_bytes)
        z.writestr("thumbnail.svg", "<svg xmlns='http://www.w3.org/2000/svg' width='128' height='128'><rect width='128' height='128' fill='black'/><text x='10' y='68' fill='white' font-size='18'>GDTF</text></svg>")
        z.writestr("readme.txt", "Generated by Auto GDTF Builder MVP. Validate in GDTF Builder / grandMA3 before production use.")
    return gdtf_buf.getvalue()
